    <h1 class="content teks-tengah ">Cerita Hidupku</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel lorem lacus. Donec in odio et lacus rutrum interdum. Nam condimentum arcu sit amet justo ullamcorper, in vulputate mi dignissim. Mauris quam nunc, molestie ac quam ut, placerat gravida metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc felis felis, fermentum ac leo ac, iaculis malesuada odio. Nunc fermentum ligula sollicitudin tincidunt tincidunt. Suspendisse a dolor pharetra, placerat metus a, elementum est. Donec dictum velit tellus, ut sollicitudin erat maximus sed. Fusce condimentum tincidunt urna, in ultricies purus pellentesque vitae. Donec augue ante, tempus quis interdum in, sodales a risus. Morbi iaculis dolor in ex mattis, quis luctus neque convallis. Curabitur eu cursus nibh, nec malesuada sapien. 
    </p>
    <p>
      Sed hendrerit mi sit amet placerat bibendum. Nullam volutpat tortor nec magna facilisis consectetur. Donec tristique ex id accumsan rutrum. Aenean nibh nisl, commodo quis nunc sed, ultrices scelerisque ipsum. Ut in erat nec lectus tincidunt ullamcorper non vel nibh. Phasellus in nisl enim. Duis ac massa vitae sapien mattis fringilla. Duis porta laoreet consequat. Maecenas pretium facilisis purus quis maximus. Curabitur ac tortor mauris. Proin vestibulum tristique lectus, in pellentesque mauris vestibulum et. Morbi pretium faucibus ligula, in fermentum massa egestas sit amet. Ut magna mi, tempus quis est non, facilisis condimentum orci. Nunc venenatis odio eget diam ullamcorper pellentesque. Vivamus aliquet, augue viverra elementum tincidunt, eros sem euismod ipsum, in laoreet velit tortor a diam. Donec sit amet augue sed tellus suscipit eleifend. 
    </p>
    <p>
      Duis dignissim sodales eros id laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus lacus metus, facilisis sit amet dui ut, porttitor sodales nunc. Fusce aliquam venenatis pellentesque. Proin porta euismod tortor, iaculis aliquet ante porttitor et. Cras posuere, neque in eleifend cursus, massa nunc viverra metus, at accumsan lorem odio et mauris. Maecenas luctus odio et turpis vulputate dignissim. Nunc sit amet justo quam. Phasellus lacinia ante non tellus luctus luctus id vitae nisi. Mauris ut turpis mattis, semper nisl eu, eleifend tellus. Donec nunc augue, congue eget purus in, tincidunt egestas augue. Fusce ut porttitor nulla, sit amet tempus massa. Nam tempus rhoncus mauris in lobortis. Vivamus ultrices justo tortor, id varius felis interdum ut. Cras vitae massa id metus ultrices faucibus. 
    </p>
    <p>
      Nullam euismod arcu non enim dictum volutpat. Praesent enim metus, maximus et massa in, dapibus malesuada nulla. Proin nunc nisl, hendrerit eget aliquam et, porttitor eget nunc. Donec ut mattis nulla. Aliquam hendrerit et velit id mollis. Suspendisse odio neque, tincidunt ac bibendum a, ullamcorper et elit. Pellentesque varius tristique ante, ac congue justo facilisis sed. Aenean nec massa pellentesque, hendrerit purus a, pretium ex. Praesent sit amet risus vitae eros iaculis efficitur sed vitae ex. Donec ullamcorper dolor sed ipsum ullamcorper varius. Sed accumsan accumsan enim, non auctor sem mattis non. Duis sem tellus, rutrum eu vestibulum nec, volutpat in eros. Vestibulum at diam eget ipsum tincidunt iaculis. Donec venenatis egestas magna, vel dapibus ante venenatis eget. Sed sit amet sodales lectus. Aliquam rhoncus ac purus et auctor.  
    </p>
    <p>
     Cras posuere maximus eleifend. Sed congue diam libero, a eleifend diam euismod quis. Donec lobortis tortor vel pharetra pulvinar. Nullam hendrerit, mauris suscipit ullamcorper dictum, velit tortor faucibus justo, a finibus neque dolor vel diam. Nullam vel erat mollis, aliquet dui non, luctus leo. Etiam quis hendrerit turpis. Mauris a egestas lorem. Mauris non placerat neque. Mauris ullamcorper augue quis magna aliquam, in varius nibh bibendum. Nulla cursus tempor cursus. Sed accumsan iaculis lectus, a efficitur nisi scelerisque nec. Nullam a dictum felis. Praesent eget lacus ex. Duis suscipit augue sit amet blandit euismod. Integer volutpat venenatis lorem ut cursus. Pellentesque nec leo purus. 
    </p>
    <p> Nunc fringilla volutpat turpis. Aenean lectus diam, commodo id ligula id, convallis luctus libero. Cras elementum, nunc vitae lacinia aliquam, ex lectus viverra lorem, a aliquam sem massa tincidunt turpis. Suspendisse lacinia magna sed auctor ultrices. Nunc ac sapien vehicula, commodo lorem sed, suscipit lorem. Fusce fringilla neque nec neque auctor, sit amet pharetra magna gravida. Sed sit amet scelerisque leo. Vivamus fermentum quam ut felis finibus ultrices. Proin pulvinar orci id sapien efficitur, nec tincidunt ex venenatis.


    </p>
    <p>
    	 Sed sed ante vitae sapien consectetur iaculis. Sed a arcu vel dui tempus fermentum. Integer ante neque, rhoncus vitae blandit laoreet, semper a tortor. Quisque et urna sed massa bibendum faucibus sollicitudin et urna. Phasellus quis sapien sapien. Morbi pretium nisi sit amet vestibulum imperdiet. In commodo, erat eu scelerisque vehicula, augue velit faucibus ex, quis dignissim augue diam eu eros. Curabitur convallis, nibh et luctus euismod, lacus risus pretium sem, id pharetra nulla dolor a libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in justo sed justo sagittis fermentum vel ac massa. Fusce ullamcorper scelerisque placerat.

    </p>